# Functions by category
asset_permissions:
- llGetInventoryPermMask
- llGetObjectPermMask
- llSetInventoryPermMask
- llSetObjectPermMask
- llTransferOwnership
attachments:
- llAttachToAvatar
- llAttachToAvatarTemp
- llDetachFromAvatar
- llGetAttached
- llGetAttachedList
- llGetAttachedListFiltered
avatar:
- llAgentInExperience
- llAttachToAvatar
- llAttachToAvatarTemp
- llAvatarOnLinkSitTarget
- llAvatarOnSitTarget
- llClearCameraParams
- llDetachFromAvatar
- llDetectedOwner
- llForceMouselook
- llGetAgentInfo
- llGetAgentLanguage
- llGetAgentList
- llGetAgentSize
- llGetAnimation
- llGetAnimationList
- llGetAnimationOverride
- llGetAttachedList
- llGetAttachedListFiltered
- llGetCameraAspect
- llGetCameraFOV
- llGetCameraPos
- llGetCameraRot
- llGetDisplayName
- llGetPermissionsKey
- llGetUsername
- llGetVisualParams
- llGiveMoney
- llIsFriend
- llName2Key
- llReleaseCamera
- llReleaseControls
- llReplaceAgentEnvironment
- llRequestAgentData
- llRequestDisplayName
- llRequestExperiencePermissions
- llRequestUserKey
- llRequestUsername
- llSetAgentEnvironment
- llSetAgentRot
- llSetCameraParams
- llStartAnimation
- llStopAnimation
- llTakeCamera
- llTakeControls
- llTeleportAgent
- llTeleportAgentGlobalCoords
- llTeleportAgentHome
- llUnSit
- llWorldPosToHUD
avatar_animation:
- llGetAnimation
- llGetAnimationList
- llGetAnimationOverride
- llResetAnimationOverride
- llSetAnimationOverride
- llStartAnimation
- llStopAnimation
avatar_communication:
- llDialog
- llEmail
- llInstantMessage
- llListen
- llListenControl
- llListenRemove
- llLoadURL
- llMapBeacon
- llMapDestination
- llOpenFloater
- llOwnerSay
- llRegionSayTo
- llSay
- llSetText
- llShout
- llTargetedEmail
- llTextBox
- llWhisper
avatar_inventory:
- llGiveAgentInventory
- llGiveInventory
- llGiveInventoryList
camera:
- llClearCameraParams
- llForceMouselook
- llGetCameraAspect
- llGetCameraFOV
- llGetCameraPos
- llGetCameraRot
- llReleaseCamera
- llSetCameraAtOffset
- llSetCameraEyeOffset
- llSetCameraParams
- llSetLinkCamera
- llTakeCamera
- llWorldPosToHUD
chat:
- llDialog
- llListen
- llListenControl
- llListenRemove
- llRegionSay
- llRegionSayTo
- llSay
- llShout
- llTextBox
- llWhisper
combat:
- llAdjustDamage
- llDamage
- llDetectedDamage
- llGetHealth
- llRezObjectWithParams
- llSetDamage
cryptography:
- llComputeHash
- llHMAC
- llHash
- llMD5String
- llSHA1String
- llSHA256String
- llSignRSA
- llVerifyRSA
data_conversion:
- llBase64ToInteger
- llBase64ToString
- llCSV2List
- llDumpList2String
- llIntegerToBase64
- llJson2List
- llJsonGetValue
- llJsonSetValue
- llJsonValueType
- llLinear2sRGB
- llList2CSV
- llList2Float
- llList2Integer
- llList2Json
- llList2Key
- llList2Rot
- llList2String
- llList2Vector
- llParseString2List
- llParseStringKeepNulls
- llStringToBase64
- llXorBase64
- llXorBase64Strings
- llXorBase64StringsCorrect
data_storage:
- llCreateKeyValue
- llDataSizeKeyValue
- llDeleteKeyValue
- llFindNotecardTextCount
- llFindNotecardTextSync
- llGetNotecardLine
- llGetNotecardLineSync
- llGetNumberOfNotecardLines
- llKeyCountKeyValue
- llKeysKeyValue
- llLinksetDataAvailable
- llLinksetDataCountFound
- llLinksetDataCountKeys
- llLinksetDataDelete
- llLinksetDataDeleteFound
- llLinksetDataDeleteProtected
- llLinksetDataFindKeys
- llLinksetDataListKeys
- llLinksetDataRead
- llLinksetDataReadProtected
- llLinksetDataReset
- llLinksetDataWrite
- llLinksetDataWriteProtected
- llReadKeyValue
- llUpdateKeyValue
dataserver:
- llCreateKeyValue
- llDataSizeKeyValue
- llDeleteKeyValue
- llFindNotecardTextCount
- llGetNotecardLine
- llGetNumberOfNotecardLines
- llKeyCountKeyValue
- llKeysKeyValue
- llReadKeyValue
- llRequestAgentData
- llRequestDisplayName
- llRequestInventoryData
- llRequestSimulatorData
- llRequestUserKey
- llRequestUsername
- llUpdateKeyValue
detected:
- llAdjustDamage
- llDetectedDamage
- llDetectedGrab
- llDetectedGroup
- llDetectedKey
- llDetectedLinkNumber
- llDetectedName
- llDetectedOwner
- llDetectedPos
- llDetectedRezzer
- llDetectedRot
- llDetectedTouchBinormal
- llDetectedTouchFace
- llDetectedTouchNormal
- llDetectedTouchPos
- llDetectedTouchST
- llDetectedTouchUV
- llDetectedType
- llDetectedVel
effects:
- llCollisionSprite
- llLinkParticleSystem
- llMakeExplosion
- llMakeFire
- llMakeFountain
- llMakeSmoke
- llParticleSystem
- llSetLinkTextureAnim
- llSetText
- llSetTextureAnim
experience:
- llAgentInExperience
- llClearExperience
- llClearExperiencePermissions
- llCreateKeyValue
- llDataSizeKeyValue
- llDeleteKeyValue
- llGetExperienceDetails
- llGetExperienceErrorMessage
- llGetExperienceList
- llKeyCountKeyValue
- llKeysKeyValue
- llReadKeyValue
- llReplaceAgentEnvironment
- llRequestExperiencePermissions
- llSetAgentEnvironment
- llSetExperienceKey
- llSitOnLink
- llUpdateKeyValue
experience_data:
- llCreateKeyValue
- llDataSizeKeyValue
- llDeleteKeyValue
- llKeyCountKeyValue
- llKeysKeyValue
- llReadKeyValue
- llUpdateKeyValue
input:
- llReleaseControls
- llSetClickAction
- llTakeControls
json:
- llJson2List
- llJsonGetValue
- llJsonSetValue
- llJsonValueType
- llList2Json
land_moderation:
- llAddToLandBanList
- llAddToLandPassList
- llEjectFromLand
- llManageEstateAccess
- llRemoveFromLandBanList
- llRemoveFromLandPassList
- llResetLandBanList
- llResetLandPassList
- llReturnObjectsByID
- llReturnObjectsByOwner
- llTeleportAgentHome
linkset:
- llAvatarOnLinkSitTarget
- llBreakAllLinks
- llBreakLink
- llClearLinkMedia
- llCreateLink
- llGetLinkKey
- llGetLinkMedia
- llGetLinkName
- llGetLinkNumberOfSides
- llGetLinkPrimitiveParams
- llGetLinkSitFlags
- llGetMass
- llGetMassMKS
- llGetMaxScaleFactor
- llGetMinScaleFactor
- llGetNumberOfPrims
- llGetObjectPermMask
- llGetOwner
- llGetRootPosition
- llGetRootRotation
- llGetStatus
- llIsLinkGLTFMaterial
- llLinkSitTarget
- llLinksetDataAvailable
- llLinksetDataCountFound
- llLinksetDataCountKeys
- llLinksetDataDelete
- llLinksetDataDeleteFound
- llLinksetDataDeleteProtected
- llLinksetDataFindKeys
- llLinksetDataListKeys
- llLinksetDataRead
- llLinksetDataReadProtected
- llLinksetDataReset
- llLinksetDataWrite
- llLinksetDataWriteProtected
- llScaleByFactor
- llSetLinkAlpha
- llSetLinkColor
- llSetLinkGLTFOverrides
- llSetLinkMedia
- llSetLinkPrimitiveParams
- llSetLinkPrimitiveParamsFast
- llSetLinkRenderMaterial
- llSetLinkSitFlags
- llSetLinkTexture
- llSetLinkTextureAnim
- llSetObjectPermMask
- llSetStatus
linkset_data:
- llLinksetDataAvailable
- llLinksetDataCountFound
- llLinksetDataCountKeys
- llLinksetDataDelete
- llLinksetDataDeleteFound
- llLinksetDataDeleteProtected
- llLinksetDataFindKeys
- llLinksetDataListKeys
- llLinksetDataRead
- llLinksetDataReadProtected
- llLinksetDataReset
- llLinksetDataWrite
- llLinksetDataWriteProtected
list:
- llDeleteSubList
- llGetListEntryType
- llGetListLength
- llList2CSV
- llList2Float
- llList2Integer
- llList2Json
- llList2Key
- llList2List
- llList2ListSlice
- llList2ListStrided
- llList2Rot
- llList2String
- llList2Vector
- llListFindList
- llListFindListNext
- llListFindStrided
- llListInsertList
- llListRandomize
- llListReplaceList
- llListSort
- llListSortStrided
- llListStatistics
math:
- llAbs
- llAcos
- llAngleBetween
- llAsin
- llAtan2
- llAxes2Rot
- llAxisAngle2Rot
- llCeil
- llCos
- llEuler2Rot
- llFabs
- llFloor
- llFrand
- llLinear2sRGB
- llListStatistics
- llLog
- llLog10
- llModPow
- llPow
- llRot2Angle
- llRot2Axis
- llRot2Euler
- llRot2Fwd
- llRot2Left
- llRot2Up
- llRotBetween
- llRound
- llSin
- llSqrt
- llTan
- llVecDist
- llVecMag
- llVecNorm
- llsRGB2Linear
math_3d:
- llAngleBetween
- llAxes2Rot
- llAxisAngle2Rot
- llEuler2Rot
- llRot2Angle
- llRot2Axis
- llRot2Euler
- llRot2Fwd
- llRot2Left
- llRot2Up
- llRotBetween
- llVecDist
- llVecMag
- llVecNorm
math_trig:
- llAcos
- llAngleBetween
- llAsin
- llAtan2
- llAxes2Rot
- llAxisAngle2Rot
- llCos
- llRot2Angle
- llRot2Axis
- llRot2Fwd
- llRot2Left
- llRot2Up
- llRotBetween
- llSin
- llTan
media:
- llClearLinkMedia
- llClearPrimMedia
- llGetLinkMedia
- llGetPrimMediaParams
- llHTTPResponse
- llParcelMediaCommandList
- llParcelMediaQuery
- llRefreshPrimURL
- llReleaseURL
- llRequestSecureURL
- llRequestURL
- llSetContentType
- llSetLinkMedia
- llSetParcelMusicURL
- llSetPrimMediaParams
- llSetPrimURL
money:
- llGiveMoney
- llSetClickAction
- llSetPayPrice
- llTransferLindenDollars
movement:
- llApplyImpulse
- llApplyRotationalImpulse
- llGetOmega
- llGetTorque
- llGetVel
- llLookAt
- llMoveToTarget
- llPointAt
- llPushObject
- llRotLookAt
- llRotTarget
- llRotTargetRemove
- llSetAgentRot
- llSetAngularVelocity
- llSetForce
- llSetForceAndTorque
- llSetHoverHeight
- llSetKeyframedMotion
- llSetLocalRot
- llSetPos
- llSetRegionPos
- llSetRot
- llSetTorque
- llSetVelocity
- llStopHover
- llStopLookAt
- llStopMoveToTarget
- llStopPointAt
- llTarget
- llTargetOmega
- llTargetRemove
notecard:
- llFindNotecardTextCount
- llFindNotecardTextSync
- llGetNotecardLine
- llGetNotecardLineSync
- llGetNumberOfNotecardLines
object:
- llGetBoundingBox
- llGetCenterOfMass
- llGetObjectDetails
- llGetObjectLinkKey
- llGetObjectMass
- llGetObjectPrimCount
- llGetOwnerKey
- llKey2Name
- llSameGroup
object_animation:
- llGetObjectAnimationNames
- llStartObjectAnimation
- llStopObjectAnimation
parcel:
- llAddToLandBanList
- llAddToLandPassList
- llEjectFromLand
- llGetAgentList
- llGetEnvironment
- llGetLandOwnerAt
- llGetMoonDirection
- llGetMoonRotation
- llGetParcelDetails
- llGetParcelFlags
- llGetParcelMaxPrims
- llGetParcelMusicURL
- llGetParcelPrimCount
- llGetParcelPrimOwners
- llGetSunDirection
- llGetSunRotation
- llOverMyLand
- llParcelMediaCommandList
- llParcelMediaQuery
- llRemoveFromLandBanList
- llRemoveFromLandPassList
- llReplaceEnvironment
- llResetLandBanList
- llResetLandPassList
- llScriptDanger
- llSetEnvironment
- llSetParcelForSale
- llSetParcelMusicURL
parcel_appearance:
- llGetEnvironment
- llGetMoonDirection
- llGetMoonRotation
- llGetSunDirection
- llGetSunRotation
- llReplaceAgentEnvironment
- llReplaceEnvironment
- llSetAgentEnvironment
- llSetEnvironment
parcel_media:
- llParcelMediaCommandList
- llParcelMediaQuery
- llSetParcelMusicURL
particles:
- llLinkParticleSystem
- llParticleSystem
pathfinding:
- llCreateCharacter
- llDeleteCharacter
- llEvade
- llExecCharacterCmd
- llFleeFrom
- llGetClosestNavPoint
- llGetStaticPath
- llNavigateTo
- llPatrolPoints
- llPursue
- llUpdateCharacter
- llWanderWithin
permissions:
- llClearCameraParams
- llForceMouselook
- llGetAnimation
- llGetAnimationList
- llGetAnimationOverride
- llGetCameraAspect
- llGetCameraFOV
- llGetCameraPos
- llGetCameraRot
- llGetPermissions
- llGetPermissionsKey
- llGiveMoney
- llReleaseCamera
- llReleaseControls
- llRequestExperiencePermissions
- llRequestPermissions
- llResetAnimationOverride
- llSetAnimationOverride
- llSetCameraParams
- llStartAnimation
- llStopAnimation
- llTakeCamera
- llTakeControls
- llTeleportAgent
- llTeleportAgentGlobalCoords
- llTransferLindenDollars
- llWorldPosToHUD
physics:
- llApplyImpulse
- llApplyRotationalImpulse
- llCastRay
- llCollisionFilter
- llCollisionSound
- llGetAccel
- llGetCenterOfMass
- llGetForce
- llGetGeometricCenter
- llGetMass
- llGetMassMKS
- llGetObjectMass
- llGetOmega
- llGetPhysicsMaterial
- llGetStatus
- llGetTorque
- llGetVel
- llLookAt
- llMoveToTarget
- llPassCollisions
- llPointAt
- llPushObject
- llRemoveVehicleFlags
- llRotLookAt
- llRotTarget
- llRotTargetRemove
- llSetAgentRot
- llSetAngularVelocity
- llSetBuoyancy
- llSetForce
- llSetForceAndTorque
- llSetHoverHeight
- llSetKeyframedMotion
- llSetPhysicsMaterial
- llSetStatus
- llSetTorque
- llSetVelocity
- llStopHover
- llStopLookAt
- llStopMoveToTarget
- llStopPointAt
- llTargetOmega
- llVolumeDetect
prim:
- llAvatarOnSitTarget
- llClearPrimMedia
- llGetAlpha
- llGetColor
- llGetCreator
- llGetKey
- llGetLinkNumber
- llGetLocalPos
- llGetLocalRot
- llGetNumberOfSides
- llGetObjectDesc
- llGetObjectName
- llGetPhysicsMaterial
- llGetPos
- llGetPrimMediaParams
- llGetPrimitiveParams
- llGetRenderMaterial
- llGetRot
- llGetScale
- llGetTexture
- llGetTextureOffset
- llGetTextureRot
- llGetTextureScale
- llOffsetTexture
- llRemoteLoadScriptPin
- llRotateTexture
- llScaleTexture
- llSetAlpha
- llSetColor
- llSetLocalRot
- llSetObjectDesc
- llSetObjectName
- llSetPhysicsMaterial
- llSetPos
- llSetPrimMediaParams
- llSetPrimURL
- llSetPrimitiveParams
- llSetRegionPos
- llSetRenderMaterial
- llSetRot
- llSetScale
- llSetSitText
- llSetTexture
- llSetTextureAnim
- llSitTarget
prim_appearance:
- llGetAlpha
- llGetColor
- llGetLinkNumberOfSides
- llGetLinkPrimitiveParams
- llGetMaxScaleFactor
- llGetMinScaleFactor
- llGetNumberOfSides
- llGetPrimitiveParams
- llGetRenderMaterial
- llGetTexture
- llGetTextureOffset
- llGetTextureRot
- llGetTextureScale
- llIsLinkGLTFMaterial
- llLinear2sRGB
- llOffsetTexture
- llRotateTexture
- llScaleByFactor
- llScaleTexture
- llSetAlpha
- llSetColor
- llSetLinkAlpha
- llSetLinkColor
- llSetLinkGLTFOverrides
- llSetLinkPrimitiveParams
- llSetLinkPrimitiveParamsFast
- llSetLinkRenderMaterial
- llSetLinkTexture
- llSetLinkTextureAnim
- llSetPrimitiveParams
- llSetRenderMaterial
- llSetScale
- llSetText
- llSetTexture
- llSetTextureAnim
- llsRGB2Linear
prim_inventory:
- llAllowInventoryDrop
- llDerezObject
- llGetInventoryAcquireTime
- llGetInventoryCreator
- llGetInventoryDesc
- llGetInventoryKey
- llGetInventoryName
- llGetInventoryNumber
- llGetInventoryPermMask
- llGetInventoryType
- llGetScriptName
- llGetScriptState
- llGiveInventory
- llGiveInventoryList
- llGodLikeRezObject
- llRemoteLoadScript
- llRemoteLoadScriptPin
- llRemoveInventory
- llRequestInventoryData
- llResetOtherScript
- llRezAtRoot
- llRezObject
- llRezObjectWithParams
- llSetInventoryPermMask
- llSetRemoteScriptAccessPin
- llSetScriptState
prim_media:
- llClearLinkMedia
- llClearPrimMedia
- llGetLinkMedia
- llGetPrimMediaParams
- llHTTPResponse
- llRefreshPrimURL
- llSetContentType
- llSetLinkMedia
- llSetPrimMediaParams
- llSetPrimURL
prim_properties:
- llGetObjectDesc
- llGetObjectDetails
- llGetObjectName
- llGetPrimitiveParams
- llSetClickAction
- llSetLinkPrimitiveParams
- llSetLinkPrimitiveParamsFast
- llSetObjectDesc
- llSetObjectName
- llSetPayPrice
- llSetPhysicsMaterial
- llSetPrimitiveParams
- llSetStatus
- llSetText
- llSetTouchText
quaternion:
- llAngleBetween
- llAxes2Rot
- llAxisAngle2Rot
- llEuler2Rot
- llRot2Angle
- llRot2Axis
- llRot2Euler
- llRot2Fwd
- llRot2Left
- llRot2Up
- llRotBetween
region:
- llCloud
- llEdgeOfWorld
- llGetAgentList
- llGetEnv
- llGetRegionAgentCount
- llGetRegionCorner
- llGetRegionDayLength
- llGetRegionDayOffset
- llGetRegionFPS
- llGetRegionFlags
- llGetRegionMoonDirection
- llGetRegionMoonRotation
- llGetRegionName
- llGetRegionSunDirection
- llGetRegionSunRotation
- llGetRegionTimeDilation
- llGetRegionTimeOfDay
- llGetSimStats
- llGetSimulatorHostname
- llGround
- llGroundContour
- llGroundNormal
- llGroundRepel
- llGroundSlope
- llModifyLand
- llRequestSimulatorData
- llSetGroundTexture
- llWater
- llWind
region_appearance:
- llGetRegionMoonDirection
- llGetRegionMoonRotation
- llGetRegionSunDirection
- llGetRegionSunRotation
- llReplaceAgentEnvironment
- llSetAgentEnvironment
rez:
- llDerezObject
- llDie
- llGetStartParameter
- llGetStartString
- llGodLikeRezObject
- llReturnObjectsByID
- llReturnObjectsByOwner
- llRezAtRoot
- llRezObject
- llRezObjectWithParams
script:
- llGetAndResetTime
- llGetEnergy
- llGetFreeMemory
- llGetFreeURLs
- llGetMemoryLimit
- llGetSPMaxMemory
- llGetScriptName
- llGetScriptState
- llGetStartParameter
- llGetStartString
- llGetTime
- llGetUsedMemory
- llMinEventDelay
- llRemoteLoadScript
- llRemoteLoadScriptPin
- llResetOtherScript
- llResetScript
- llResetTime
- llScriptDanger
- llScriptProfiler
- llSetMemoryLimit
- llSetRemoteScriptAccessPin
- llSetScriptState
- llSetTimerEvent
- llSleep
script_communication:
- llCloseRemoteDataChannel
- llGetNextEmail
- llHTTPRequest
- llHTTPResponse
- llListen
- llListenControl
- llListenRemove
- llMessageLinked
- llOpenRemoteDataChannel
- llRegionSay
- llRegionSayTo
- llRemoteDataReply
- llRemoteDataSetRegion
- llRequestSecureURL
- llRequestURL
- llSay
- llSendRemoteData
- llShout
- llWhisper
sensor:
- llCastRay
- llCollisionFilter
- llPassCollisions
- llSensor
- llSensorRemove
- llSensorRepeat
- llVolumeDetect
sit:
- llAvatarOnLinkSitTarget
- llAvatarOnSitTarget
- llGetLinkSitFlags
- llLinkSitTarget
- llSetLinkCamera
- llSetLinkSitFlags
- llSetSitText
- llSitOnLink
- llSitTarget
- llUnSit
sound:
- llAdjustSoundVolume
- llCollisionSound
- llCollisionSprite
- llLinkAdjustSoundVolume
- llLinkPlaySound
- llLinkSetSoundQueueing
- llLinkSetSoundRadius
- llLinkStopSound
- llLoopSound
- llLoopSoundMaster
- llLoopSoundSlave
- llPlaySound
- llPlaySoundSlave
- llPreloadSound
- llSetSoundQueueing
- llSetSoundRadius
- llSound
- llSoundPreload
- llStopSound
- llTriggerSound
- llTriggerSoundLimited
string:
- llChar
- llDeleteSubString
- llGetSubString
- llInsertString
- llOrd
- llReplaceSubString
- llStringLength
- llStringTrim
- llSubStringIndex
- llToLower
- llToUpper
teleport:
- llMapDestination
- llTeleportAgent
- llTeleportAgentGlobalCoords
- llTeleportAgentHome
time:
- llGetDate
- llGetDayLength
- llGetDayOffset
- llGetGMTclock
- llGetRegionDayLength
- llGetRegionDayOffset
- llGetRegionTimeOfDay
- llGetTimeOfDay
- llGetTimestamp
- llGetUnixTime
- llGetWallclock
- llSetTimerEvent
- llSleep
touch:
- llDetectedGrab
- llDetectedTouchBinormal
- llDetectedTouchFace
- llDetectedTouchNormal
- llDetectedTouchPos
- llDetectedTouchST
- llDetectedTouchUV
- llPassTouches
- llSetClickAction
- llSetTouchText
user_interface:
- llDialog
- llLoadURL
- llMapBeacon
- llMapDestination
- llSetClickAction
- llSetPayPrice
- llSetSitText
- llSetTouchText
- llTextBox
- llWorldPosToHUD
uuid:
- llDetectedKey
- llGenerateKey
- llGetKey
- llGetLinkKey
- llGetObjectLinkKey
- llGetOwner
- llGetOwnerKey
- llRequestUserKey
vector:
- llRot2Axis
- llRot2Fwd
- llRot2Left
- llRot2Up
- llVecDist
- llVecMag
- llVecNorm
vehicles:
- llRemoveVehicleFlags
- llSetVehicleFlags
- llSetVehicleFloatParam
- llSetVehicleRotationParam
- llSetVehicleType
- llSetVehicleVectorParam
web:
- llEscapeURL
- llGetFreeURLs
- llGetHTTPHeader
- llHTTPRequest
- llHTTPResponse
- llLoadURL
- llRefreshPrimURL
- llReleaseURL
- llRequestSecureURL
- llRequestURL
- llSetContentType
- llSetLinkMedia
- llSetPrimMediaParams
- llSetPrimURL
- llUnescapeURL
