"""Generator for builtins.txt (LSLint-compatible format)."""

from __future__ import annotations

import json

from lsl_definitions.generators.base import register
from lsl_definitions.lsl import LSLDefinitions, LSLType


@register("gen_builtins_txt")
def gen_builtins_txt(definitions: LSLDefinitions) -> str:
    """Generate builtins.txt for LSLint-compatible implementations"""
    # See https://github.com/Sei-Lisa/kwdb/blob/master/outputs/builtins.txt for an example
    builtins_str = "// Generated by gen_definitions.py\n"

    for func in sorted(definitions.functions.values(), key=lambda x: x.name):
        builtins_str += f"{func.ret_type!s} {func.name}{func.args_str}\n"

    for const in sorted(definitions.constants.values(), key=lambda x: x.name):
        builtins_str += f"const {const.type!s} {const.name} = "
        if const.type == LSLType.STRING:
            # We don't use C encoding semantics to escape values because LSL only knows
            # about a handful of basic escapes like `\n`.
            # Other values we want to output verbatim.
            lsl_val = const.value_raw.replace("\n", "\\n")
            builtins_str += f'"{lsl_val}"'
        else:
            builtins_str += const.value
        builtins_str += "\n"

    for event in sorted(definitions.events.values(), key=lambda x: x.name):
        builtins_str += f"event {event.name}{event.args_str}\n"

    return builtins_str


@register("gen_enum_users")
def gen_enum_users(definitions: LSLDefinitions) -> str:
    # List of all enum users. Feel free to remove this rule
    out = {enum.name: [] for enum in sorted(definitions.enums.values(), key=lambda x: x.name)}

    for func in sorted(definitions.functions.values(), key=lambda x: x.name):
        for arg in func.arguments:
            if arg.enum_semantics:
                out[arg.enum_semantics.name].append(func.name)
            if arg.param_semantics:
                out[arg.param_semantics.name].append(func.name)
            if arg.param_get_semantics:
                out[arg.param_get_semantics.name].append(func.name)

    return json.dumps(out, indent=2)
