"""Generator for builtins.txt (LSLint-compatible format)."""

from __future__ import annotations

import json

from lsl_definitions.generators.base import register
from lsl_definitions.lsl import LSLDefinitions, LSLEnumType, LSLType


@register("gen_builtins_txt")
def gen_builtins_txt(definitions: LSLDefinitions) -> str:
    """Generate builtins.txt for LSLint-compatible implementations"""
    # See https://github.com/Sei-Lisa/kwdb/blob/master/outputs/builtins.txt for an example
    builtins_str = "// Generated by gen_definitions.py\n"

    for func in sorted(definitions.functions.values(), key=lambda x: x.name):
        args_str = ", ".join(f"{x.type!s} {x.name}" for x in func.arguments)
        builtins_str += f"{func.ret_type!s} {func.name}( {args_str} )\n"

    for const in sorted(definitions.constants.values(), key=lambda x: x.name):
        builtins_str += f"const {const.type!s} {const.name} = "
        if const.type == LSLType.STRING:
            # We don't use C encoding semantics to escape values because LSL only knows
            # about a handful of basic escapes like `\n`.
            # Other values we want to output verbatim.
            lsl_val = const.value_raw.replace("\n", "\\n")
            builtins_str += f'"{lsl_val}"'
        else:
            builtins_str += const.value
        builtins_str += "\n"

    for event in sorted(definitions.events.values(), key=lambda x: x.name):
        args_str = ", ".join(f"{x.type!s} {x.name}" for x in event.arguments)
        builtins_str += f"event {event.name}( {args_str} )\n"

    return builtins_str


@register("gen_enums_txt")
def gen_enums_txt(definitions: LSLDefinitions) -> str:
    builtins_str = "// Dump of the enums just for testing. Feel free to remove this rule\n"

    for enum in sorted(definitions.enums.values(), key=lambda x: x.name):
        builtins_str += f"enum {enum.name!s} {{\n"
        for member in sorted(enum.members, key=lambda x: x.value):
            builtins_str += f"  {member.name} = "
            if enum.type == LSLEnumType.FLAG:
                builtins_str += f"0x{member.value:x}"
            else:
                builtins_str += f"{member.value}"
            if member.constant.private:
                builtins_str += " // private"
            if member.constant.deprecated:
                builtins_str += " // deprecated"
            builtins_str += "\n"
        builtins_str += "};\n"

    for const in sorted(definitions.constants.values(), key=lambda x: x.name):
        if not const.member_of:
            builtins_str += f"const {const.type!s} {const.name} = {const.lsl_doc_literal}"
            if const.private:
                builtins_str += " // private"
            if const.deprecated:
                builtins_str += " // deprecated"
            builtins_str += "\n"

    return builtins_str


@register("gen_enum_users")
def gen_enum_users(definitions: LSLDefinitions) -> str:
    # List of all enum users. Feel free to remove this rule
    out = {enum.name: [] for enum in sorted(definitions.enums.values(), key=lambda x: x.name)}

    for func in sorted(definitions.functions.values(), key=lambda x: x.name):
        for arg in func.arguments:
            if arg.enum_semantics:
                out[arg.enum_semantics.name].append(func.name)
            if arg.param_semantics:
                out[arg.param_semantics.name].append(func.name)
            if arg.param_get_semantics:
                out[arg.param_get_semantics.name].append(func.name)

    return json.dumps(out, indent=2)
