<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lsl</string>
		<string>lslp</string>
		<string>lslm</string>
		<string>lslo</string>
		<string>esl</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>Second Life LSL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#round-brackets</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>match</key>
			<string>==|!=</string>
			<key>name</key>
			<string>keyword.operator.comparison.lsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[-+*/%]?=</string>
			<key>name</key>
			<string>keyword.operator.assignment.lsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\|\|?|\^|&amp;&amp;?|!|~</string>
			<key>name</key>
			<string>keyword.operator.logical.lsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+\+?|\-\-?|&lt;&lt;|&gt;&gt;|&lt;=|&gt;=|&lt;|&gt;|\*|/|%</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.lsl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.jump.lsl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.reference.label.lsl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(jump)\s+([a-zA-Z_][a-zA-Z_0-9]*\b)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>LSL Flow-control keywords</string>
			<key>match</key>
			<string>\b$LSL_FLOW_CONTROL_REGEX\b</string>
			<key>name</key>
			<string>keyword.control.lsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>LSL Types</string>
			<key>match</key>
			<string>\b$LSL_TYPES_REGEX\b</string>
			<key>name</key>
			<string>storage.type.lsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>LSL Constants</string>
			<key>match</key>
			<string>\b(TRUE|FALSE)\b</string>
			<key>name</key>
			<string>constant.language.boolean.lsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>LSL Events</string>
			<key>match</key>
			<string>\b$LSL_EVENTS_REGEX\b</string>
			<key>name</key>
			<string>constant.language.events.lsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>LSL Functions ll*</string>
			<key>match</key>
			<string>(?x)\b$LSL_FUNCTIONS_REGEX\b</string>
			<key>name</key>
			<string>support.function.lsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>LSL Functions only available to certain Linden Lab employees</string>
			<key>match</key>
			<string>(?x)\b$LSL_FUNCTIONS_GOD_MODE_REGEX\b</string>
			<key>name</key>
			<string>support.function.god-mode.lsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)\b$LSL_FUNCTIONS_DEPRECATED_REGEX\b</string>
			<key>name</key>
			<string>invalid.deprecated.support.function.lsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)\b$LSL_FUNCTIONS_ILLEGAL_REGEX\b</string>
			<key>name</key>
			<string>invalid.illegal.reserved-function.lsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>LSL Function Constants</string>
			<key>match</key>
			<string>(?x)\b$LSL_FUNCTION_CONSTANTS_REGEX\b</string>
			<key>name</key>
			<string>support.constant.lsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)\b$LSL_CONSTANTS_DEPRECATED_REGEX\b</string>
			<key>name</key>
			<string>invalid.deprecated.constant.lsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[a-zA-Z_][a-zA-Z_0-9]*(?=\s*\()</string>
			<key>name</key>
			<string>entity.name.function.lsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[a-zA-Z_][a-zA-Z_0-9]*\b</string>
			<key>name</key>
			<string>variable.other.lsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\B@[a-zA-Z_][a-zA-Z_0-9]*\b</string>
			<key>name</key>
			<string>constant.other.reference.label.lsl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lsl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lsl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.lsl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[\\"nt]</string>
					<key>name</key>
					<string>constant.character.escape.lsl</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.lsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.lsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.lsl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=//)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.lsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>//</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.lsl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.double-slash.lsl</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b0(x|X)[0-9a-fA-F]+\b</string>
					<key>name</key>
					<string>constant.numeric.integer.hexadecimal.lsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[0-9]+([Ee][-+]?[0-9]+)\b</string>
					<key>name</key>
					<string>constant.numeric.float.lsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([0-9]+\.[0-9]*|[0-9]*\.[0-9]+)([Ee][-+]?[0-9]+)?[fF]?\b</string>
					<key>name</key>
					<string>constant.numeric.float.lsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.integer.lsl</string>
				</dict>
			</array>
		</dict>
		<key>round-brackets</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.begin.lsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.end.lsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.block.lsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.group.begin.lsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.group.end.lsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.group.parenthesis.lsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.array.begin.lsl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.array.end.lsl</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.array.lsl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lsl</string>
	<key>uuid</key>
	<string>21B2E01B-B911-4B99-975E-4787BEAE6697</string>
</dict>
</plist>
